conditional-push30

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -7,45 +7,52 @@ jobs:
       - image: "circleci/node:9.6.1"
     description: "Record changes and persist result to workspace"
     steps:
-#      - run: echo 'there were changes' > '/tmp/check_for_changes.txt'
-      - run: touch '/tmp/check_for_changes.txt'
+      - run:
+          echo 'export CHANGES=HELLO' > '/tmp/load_change_status.sh'
       - persist_to_workspace:
           root: /tmp
           paths:
-            - check_for_changes.txt
+            - load_change_status.sh
 
-  check_for_changes:
-    docker:
-      - image: "circleci/node:9.6.1"
-    description: "Check for changes"
-    steps:
-      - attach_workspace:
-          at: /tmp
-      - run: |
-          CHANGES=`cat /tmp/check_for_changes.txt | awk '{print length}'`
-          if [[ ${#CHANGES} -gt 0 ]]
-          then
-            echo "There were changes"
-            exit 0
-          else
-            echo "There were no changes"
-            exit 1
-          fi
+#  check_for_changes:
+#    docker:
+#      - image: "circleci/node:9.6.1"
+#    description: "Check for changes"
+#    steps:
+#      - attach_workspace:
+#          at: /tmp
+#      - run: |
+#          CHANGES=`cat /tmp/check_for_changes.txt | awk '{print length}'`
+#          if [[ ${#CHANGES} -gt 0 ]]
+#          then
+#            echo "There were changes"
+#            exit 0
+#          else
+#            echo "There were no changes"
+#            exit 1
+#          fi
 
   downstream_job:
     docker:
       - image: "circleci/node:9.6.1"
     description: "Only run if there are changes"
     steps:
+      - attach_workspace:
+          at: /tmp
+      - run: source /tmp/load_change_status.sh
+      - run: |
+          if [[ ${CHANGES} == 'HELLO' ]]
+          then
+            echo 'woo'
+          else
+            echo 'fail'
+          fi
       - run: echo "downstream job ran"
 
 workflows:
   test:
     jobs:
       - record_changes
-      - check_for_changes:
-          requires:
-            - record_changes
       - downstream_job:
           requires:
-            - check_for_changes
+            - record_changes
